[package]
name = "vault_core"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10"
aes = "0.8"
rand = "0.8"
argon2 = "0.5"
base64 = "0.21"
ed25519-dalek = "1.0"
sha2 = "0.10"
zeroize = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
